<?xml version="1.0"?>
<package format="2">
  <name>screen_grab</name>
  <version>0.0.2</version>
  <description>Publish a screen capture as an Image</description>

  <maintainer email="lucasw_backwards@gmail.com">Lucas Walter</maintainer>
  <license>BSD</license>

  <url type="website">https://github.com/lucasw/screen_grab</url>

  <!-- Build tool -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Dependencies for build -->
  <build_depend>cv_bridge</build_depend>
  <build_depend>dynamic_reconfigure</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>nodelet</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>roslint</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>std_msgs</build_depend>

  <!-- Dependencies for execution -->
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>dynamic_reconfigure</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>nodelet</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <nodelet plugin="${prefix}/nodelet_screen_grab.xml"/>
    <nodelet plugin="${prefix}/nodelet_image_show.xml"/>
  </export>
</package>
